zh_en_map = {
    "鄉鎮市區": "district",
    "交易標的": "object_of_transaction",
    "土地位置建物門牌": "location",
    "土地移轉總面積平方公尺": "land_total_area",
    "交易年月日": "transaction_date",
    "移轉層次": "level",
    "總樓層數": "total_floor_numbers",
    "建物型態": "building_state",
    "主要用途": "main_use",
    "建物移轉總面積平方公尺": "building_total_area",
    "建物現況格局-房": "room",
    "建物現況格局-廳": "restaurant_and_living_room",
    "建物現況格局-衛": "bathroom",
    "總價元": "price",
    "單價元平方公尺": "unit_price",
    "車位類別": "parking_sapce_type",
    "車位移轉總面積平方公尺": "parking_sapce_total_area",
    "車位總價元": "parking_sapce_price",
    "備註": "note",
    "建案名稱": "build_name",
    "棟及號": "buildings",
}
